export const courses = [
    {
        title: "Complete Web Design: From Figma to Webflow - 2024 UI",
        thumbnail: "/images/course-thumbnail.png",
        totalHours: "21.5",
        updatedDate: "11/2024",
        rating: 4.8,
        totalStudents: 86182,
        discountedPrice: "$11.99",
        originalPrice: "$74.99",
        isInWishlist: false,
    },
    {
        title: "Mastering React and Redux - 2024 Edition",
        thumbnail: "/images/react-redux-course.png",
        totalHours: "35",
        updatedDate: "09/2024",
        rating: 4.7,
        totalStudents: 54012,
        discountedPrice: "$9.99",
        originalPrice: "$59.99",
        isInWishlist: true,
    },
    {
        title: "JavaScript Essentials: From Zero to Hero",
        thumbnail: "/images/js-essentials.png",
        totalHours: "18",
        updatedDate: "10/2024",
        rating: 4.5,
        totalStudents: 120343,
        discountedPrice: "$12.99",
        originalPrice: "$69.99",
        isInWishlist: false,
    },
    {
        title: "Advanced CSS and SASS: Flexbox, Grid, Animations",
        thumbnail: "/images/css-advanced.png",
        totalHours: "14",
        updatedDate: "08/2024",
        rating: 4.6,
        totalStudents: 48301,
        discountedPrice: "$13.99",
        originalPrice: "$49.99",
        isInWishlist: true,
    },
    {
        title: "Python for Data Science and Machine Learning Bootcamp",
        thumbnail: "/images/python-data-science.png",
        totalHours: "40",
        updatedDate: "07/2024",
        rating: 4.8,
        totalStudents: 102384,
        discountedPrice: "$10.99",
        originalPrice: "$89.99",
        isInWishlist: false,
    },
    {
        title: "Full-Stack Web Development with Node and Express",
        thumbnail: "/images/fullstack-node.png",
        totalHours: "30",
        updatedDate: "06/2024",
        rating: 4.9,
        totalStudents: 79832,
        discountedPrice: "$14.99",
        originalPrice: "$99.99",
        isInWishlist: true,
    },
    {
        title: "UI/UX Design Fundamentals - Sketch, Figma, and Adobe XD",
        thumbnail: "/images/ui-ux-fundamentals.png",
        totalHours: "15",
        updatedDate: "11/2024",
        rating: 4.7,
        totalStudents: 67431,
        discountedPrice: "$9.99",
        originalPrice: "$59.99",
        isInWishlist: false,
    },
    {
        title: "The Complete Guide to Front-End Development - 2024",
        thumbnail: "/images/frontend-development.png",
        totalHours: "27",
        updatedDate: "05/2024",
        rating: 4.8,
        totalStudents: 91542,
        discountedPrice: "$12.99",
        originalPrice: "$74.99",
        isInWishlist: true,
    },
];
