const courses = [
    {
        image: "/images/course-thumbnail.png",
        logo: "/images/course-thumbnail.png",
        title: "Complete A.I. & Machine Learning, Data Science...",
        instructors: ["Andrei Neagoie", "Daniel Bourke"],
        rating: 4.6,
        reviews: 24457,
        totalHours: "44",
        lectures: "384",
        level: "All Levels",
        currentPrice: 11.99,
        originalPrice: 74.99,
    },
    {
        image: "/images/course-thumbnail-2.png",
        logo: "/images/course-logo-2.png",
        title: "JavaScript: The Advanced Concepts (2023 Edition)",
        instructors: ["Andrei Neagoie"],
        rating: 4.8,
        reviews: 18257,
        totalHours: "30",
        lectures: "260",
        level: "Intermediate",
        currentPrice: 13.99,
        originalPrice: 69.99,
    },
    {
        image: "/images/course-thumbnail-3.png",
        logo: "/images/course-logo-3.png",
        title: "The Complete Python Developer in 2023",
        instructors: ["Daniel Bourke", "Jane Doe"],
        rating: 4.7,
        reviews: 32561,
        totalHours: "50",
        lectures: "420",
        level: "All Levels",
        currentPrice: 10.99,
        originalPrice: 89.99,
    },
    {
        image: "/images/course-thumbnail-4.png",
        logo: "/images/course-logo-4.png",
        title: "Web Development Bootcamp 2023",
        instructors: ["Angela Yu"],
        rating: 4.9,
        reviews: 30210,
        totalHours: "55",
        lectures: "480",
        level: "Beginner",
        currentPrice: 12.99,
        originalPrice: 79.99,
    },
    {
        image: "/images/course-thumbnail-5.png",
        logo: "/images/course-logo-5.png",
        title: "Mastering React and Redux Toolkit",
        instructors: ["Maximilian Schwarzmüller"],
        rating: 4.5,
        reviews: 19560,
        totalHours: "35",
        lectures: "310",
        level: "Intermediate",
        currentPrice: 14.99,
        originalPrice: 64.99,
    },
];
